name: flutter_easy_translate
description: Flutter Easy Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 1.0.4
homepage: https://github.com/belabiedredouane
repository: https://github.com/belabiedredouane/flutter_easy_translate
issue_tracker: https://github.com/belabiedredouane/flutter_easy_translate/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: Flutter easy translate logo.
    path: resources/images/logo.png
