name: flutter_easy_translate
description: Flutter Easy Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 1.0.5
homepage: https://github.com/belabiedredouane
repository: https://github.com/belabiedredouane/flutter_easy_translate
issue_tracker: https://github.com/belabiedredouane/flutter_easy_translate/issues
topics: [i18n, translation, localization, locale, internationalization, translate, flutter-translate, easy-translate, easy-localization, json, flutter-localizations, language]

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  universal_io: ^2.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: Flutter easy translate logo.
    path: resources/images/logo.png
