name: flutter_easy_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 0.1.0
homepage: https://github.com/belabiedredouane
repository: https://github.com/belabiedredouane/flutter_easy_translate

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
